# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ebdac5734b727f50db4981984361225"
name = "LiveWellRx"
handle = "livewellrx"
application_url = "https://contemporary-settlement-photos-recognize.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_metaobjects,write_metaobjects,read_customers"

[auth]
redirect_urls = ["https://contemporary-settlement-photos-recognize.trycloudflare.com/auth/callback", "https://contemporary-settlement-photos-recognize.trycloudflare.com/auth/shopify/callback", "https://contemporary-settlement-photos-recognize.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
